language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements/dev.txt

script:
  - "PYTHONPATH=courses DJANGO_SETTINGS_MODULE=courses.settings.base django-admin test courses"

notifications:
  webhooks:
    urls:
      - http://staging-learn.rmotr.com/webhooks/travis/build-finished
    on_success: always
    on_failure: always
    on_start: never
